package kanban.view;

import java.time.LocalDate;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;
import kanban.Conexao;
import kanban.entidades.*;

/**
 *
 * @author windows
 */
public class KanbanTela extends javax.swing.JFrame {
    Board b = new Board("Projeto 1");
    Conexao conn = new Conexao();
    public KanbanTela() {
        initComponents();
        
        conn.preencheLista(b.fazer, 1);
        fazer.setModel(b.fazer);
        
        conn.preencheLista(b.analise, 2);
        analise.setModel(b.analise);
        
        conn.preencheLista(b.dev, 3);
        dev.setModel(b.dev);
        
        conn.preencheLista(b.teste, 4);
        teste.setModel(b.teste);
        
        conn.preencheLista(b.finalizado, 5);
        finalizado.setModel(b.finalizado);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fazer = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        analise = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        dev = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        teste = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        finalizado = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        taskConfirm = new javax.swing.JButton();
        txtTask = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setToolTipText("");
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        fazer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fazer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fazerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fazer);

        jPanel1.add(jScrollPane1);

        analise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        analise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                analiseMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(analise);

        jPanel1.add(jScrollPane2);

        dev.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                devMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(dev);

        jPanel1.add(jScrollPane3);

        teste.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        teste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testeMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(teste);

        jPanel1.add(jScrollPane4);

        finalizado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        finalizado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finalizadoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(finalizado);

        jPanel1.add(jScrollPane5);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("A fazer");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Análise");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Desenvolvimento");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Teste");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel4);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Finalizado");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel5);

        taskConfirm.setText("Adicionar");
        taskConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtTask, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(taskConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listMouseClicked(java.awt.event.MouseEvent evt, JList<Task> sourceList, JList<Task> destinationList, DefaultListModel<Task> sourceModel, DefaultListModel<Task> destinationModel) {                                   
        int selectedIndex = sourceList.getSelectedIndex();
        if (selectedIndex != -1) {
            Task task = sourceModel.getElementAt(selectedIndex);
            b.moveTarefa(sourceModel, destinationModel, task);
            conn.updateTask(task);
        }
    }
    
    private void taskConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskConfirmActionPerformed
        Task t = new Task(txtTask.getText(),1);
        b.addTarefa(b.fazer, t);
        txtTask.setText(""); 
        conn.insertTask(t,t.getEstado());
    }//GEN-LAST:event_taskConfirmActionPerformed
    
    private void fazerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fazerMouseClicked
        listMouseClicked(evt, fazer, analise, b.fazer, b.analise);
    }//GEN-LAST:event_fazerMouseClicked

    private void analiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analiseMouseClicked
        listMouseClicked(evt, analise, dev,b.analise, b.dev);
    }//GEN-LAST:event_analiseMouseClicked

    private void devMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devMouseClicked
        listMouseClicked(evt, dev, teste, b.dev, b.teste);
    }//GEN-LAST:event_devMouseClicked

    private void testeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testeMouseClicked
        listMouseClicked(evt, teste, finalizado, b.teste, b.finalizado);
    }//GEN-LAST:event_testeMouseClicked

    private void finalizadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finalizadoMouseClicked
        int selectedIndex = finalizado.getSelectedIndex();
        if(selectedIndex != -1) {
            Task task = b.finalizado.getElementAt(selectedIndex);
            b.removeTarefa(b.finalizado, task);
            conn.updateTask(task);
        }
    }//GEN-LAST:event_finalizadoMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Task> analise;
    private javax.swing.JList<Task> dev;
    private javax.swing.JList<Task> fazer;
    private javax.swing.JList<Task> finalizado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton taskConfirm;
    private javax.swing.JList<Task> teste;
    private javax.swing.JTextField txtTask;
    // End of variables declaration//GEN-END:variables
}
